const lines = [
    "Hi, 3 just joined ? ",
    "Hi, who just joined ? ",
    "Hi, 4o just joined ? ",
    "Hi, w5 just joined ? ",
    "Hi, who just joined ? ",
    "Hi, who just joined ? ",
    "Hi, r just joined ? ",
    "Hi, who just joined ? ",
    "Hi, who just joined ? ",
    "Hi, wto just joined ? ",
    "Hi, who just joined ? ",
    "Hi, wyy just joined ? ",
    "Hi, uyuo just joined ? ",
    "Hi, who just joined ? ",
    "Hi, yuyuo just joined ? ",
    "Hi, who just joined ? ",
    "Hi, who just joined ? ",
    "Hi, yuyuyuo just joined ? ",
    "Hi, who just joined ? ",
    "Hi, who just joined ? ",
    "Hi, yuo just joined ? ",
    "Hi, wyyo just joined ? ",
    "Hi, who just joined ? ",
    "Hi, wyu just joined ? ",
    "Hi, wyuyu just joined ? ",
];

export default lines;